Configuration;

fprintf('=== Generating kCCA input ===\n\n');
fprintf('Fixed conditions, marginalizing over movies\n');
%for depthcond = 0:1
%	for colorcond = 0:1
%		gen_cca_input_fixed_conditions(config, colorcond, depthcond);
%	end
%end
fprintf('Fixed movies, marginalizing over conditions\n');
%for movie_id = 1:3
%	gen_cca_input_fixed_movie(config, movie_id);
%end

%fprintf('=== Calculating Brain Activation Pattern for fixed conditions, marginalizing over movies ===\n\n');
%gen_sqr_pattern(config,...
%				 config.cca_input_fixed_conditions_dir,...
%				 config.cca_output_fixed_conditions_dir,...
%				 config.num_components);
%		
%fprintf('=== Calculating Brain Activation Pattern for fixed movies, marginalizing over conditions===\n\n'); 
%gen_sqr_pattern(config,...
%				 config.cca_input_fixed_movie_dir,...
%				 config.cca_output_fixed_movie_dir,...
%				 config.num_components);

%fprintf('\n\n=== Average Activation: Fixed conditions, marginalizing over movies ===\n\n');
%gen_average_activation_pattern(config, config.cca_output_fixed_conditions_dir, config.av_act_fixed_conditions_dir)
%fprintf('\n\n=== Average Activation: Fixed movies, marginalizing over conditions ===\n\n');
%gen_average_activation_pattern(config, config.cca_output_fixed_movie_dir, config.av_act_fixed_movie_dir)

fprintf('Calculating correlations for the fixed conditions experiments\n');
simple_correlation(config.input_subject_data_dir,...
					config.av_act_fixed_conditions_dir,...
					config.input_nsynth_pattern_dir,...
					config.simple_correlation_output_fixed_conditions_dir,...
					config.input_nsynth_nifti_dir);
fprintf('\n\nCalculating correlations for the fixed movie experiments\n\n');
simple_correlation(config.input_subject_data_dir,...
					config.av_act_fixed_movie_dir,...
					config.input_nsynth_pattern_dir,...
					config.simple_correlation_output_fixed_movie_dir,...
					config.input_nsynth_nifti_dir);


